# Generated by Django 4.1.3 on 2022-12-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_ebook_alter_genre_options_delete_product_ebook_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='created',
            new_name='date_added',
        ),
    ]
