# Generated by Django 4.1.3 on 2022-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_created_ebook_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='isbn',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=13),
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='genre',
        ),
        migrations.AddField(
            model_name='ebook',
            name='genre',
            field=models.ManyToManyField(to='store.genre'),
        ),
    ]
