# Generated by Django 4.1.3 on 2022-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_ebook_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='genre',
        ),
        migrations.AddField(
            model_name='ebook',
            name='genre',
            field=models.ManyToManyField(to='store.genre'),
        ),
    ]
