# Generated by Django 4.1.3 on 2022-12-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ebook',
            new_name='book',
        ),
    ]
